### ISSUE TITLE
AppVeyor build doesn't find test logs

### ISSUE THREAD

**Issue by christianspecht** [christianspecht/scm-backup#75]
Example:

https://ci.appveyor.com/project/ChristianSpecht/scm-backup/builds/47343251

```
Everything is Ok
Collecting artifacts...
Found artifact 'release\scm-backup-0.0.0.CI-WIN-188-1dc9b2c.zip' matching 'release\scm-backup-*.zip' path
No artifacts found matching 'src\ScmBackup.Tests.Integration\bin\Release\netcoreapp3.1\*.log' path
Uploading artifacts...
[1/1] release\scm-backup-0.0.0.CI-WIN-188-1dc9b2c.zip (3,081,555 bytes)...100%
```

The [Linux build for the same commit](https://github.com/christianspecht/scm-backup/actions/runs/5316979910/jobs/9627023324) finds the logfile:

```
Run actions/upload-artifact@v3
  with:
    name: Test log
    path: src/ScmBackup.Tests.Integration/bin/Release/netcoreapp3.1/*.log
    if-no-files-found: warn
  env:
    DOTNET_ROOT: /usr/share/dotnet
    ScmBackupCommit: 1dc9b2c
    ScmBackupShortVersion: 0.0.0
    ScmBackupLongVersion: 0.0.0.CI-LINUX-25-1dc9b2c
With the provided path, there will be 1 file uploaded
Starting artifact upload
```

When running the tests locally, the logfile is created.

TODO: find out why it's not created or found on AppVeyor
